### PR TITLE
Temp files, Force Text Serialization

### PR DESCRIPTION
**Pull request by ChrisClark13**
I put "temp" files in each of the missing empty folders so that git will keep them around. Otherwise several errors occur where there are .meta files for non existent folders.

I also set Asset Serialization to "Force Text" rather than letting Unity pick between Text and Binary whenever it feels like it. It's recommended to use Text Seralization for git projects with Unity.

Also "YourNameDino" was misspelled as "YiurNameDino"

### CODE REVIEW

**Comment by ChrisClark13** [comment]
http://answers.unity3d.com/questions/222281/asset-serialization-mixed-vs-force-text.html
Provides good reasons to use Text Serialization

In short: It's easy to see the scope of and changes what was changes in git, commits are small, Scene files don't show as being changed when someone just opens the file just to look around the scene.

**Comment by anthonyromrell** [comment]
I won't accept this request until you address the conflicts listed.

**Comment by ChrisClark13** [comment]
Should be all ready to go! Merge will replace the binary asset files with the text asset files.

**Comment by ChrisClark13** [comment]
blargh, too much stuff changing I'll just rebase later

**Pull request closed without merging**
